mysql:
  container_name: mysql_with_data
  restart: always
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: 'paweltest' # TODO: Change this
    MYSQL_USER: 'test'
    MYSQL_PASS: 'pass'
  volumes:
    - ./data:/var/lib/mysql
  ports:
    - 3306:3306
